FROM node:16-alpine

# Crear directorio de trabajo
WORKDIR /usr/src/app

# Instalar dependencias
COPY package*.json ./
RUN npm install --only=production

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto
EXPOSE 8081

# Comando para ejecutar la aplicación
CMD ["node", "app1.js"]
